apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hellogo
  namespace: hellogo
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/paulovigne/hellogo-pipeline-k8s.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:6c3980b3d28c8fb92b17466f5654d5f484ab893f1673ec8f29e49c0d03f8aca9
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline
    - name: buildah
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/hellogo/hellogo'
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: STORAGE_DRIVER
          value: vfs
        - name: DOCKERFILE
          value: ./Dockerfile.openshift
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: FORMAT
          value: oci
        - name: SKIP_PUSH
          value: 'false'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline
    - name: create-deploy
      params:
        - name: SCRIPT
          value: >-
            oc create deployment hellogo
            --image=image-registry.openshift-image-registry.svc:5000/hellogo/hellogo
            --dry-run=client -o yaml | oc apply -f -
        - name: VERSION
          value: latest
      runAfter:
        - buildah
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: create-svc
      params:
        - name: SCRIPT
          value: >-
            oc expose deployment hellogo --port=8080 --dry-run=client -o yaml |
            oc apply -f -
        - name: VERSION
          value: latest
      runAfter:
        - create-deploy
      taskRef:
        kind: ClusterTask
        name: openshift-client
    - name: create-route
      params:
        - name: SCRIPT
          value: >-
            oc expose svc hellogo --name hellogo --dry-run=client -o yaml | oc
            apply -f -
        - name: VERSION
          value: latest
      runAfter:
        - create-svc
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: pipeline